set(SPINspiral_src_files
  src/SPINspiral_3rdparty.c  
  src/SPINspiral_data.c  
  src/SPINspiral_lal.c  
  src/SPINspiral_main.c  
  src/SPINspiral_mcmc.c  
  src/SPINspiral_parameters.c  
  src/SPINspiral_routines.c  
  src/SPINspiral_signal.c  
  src/SPINspiral_templates.c
  )
